---
- name: "template for main nginx configuration"
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  when: main_template_enable
  notify: "reload nginx"

- name: "ensure sites-* directories exists"
  file:
    path: {{ item }}
    state: directory
  with_items: 
    - "/etc/nginx/sites-enabled"
    - "/etc/nginx/sites-available"

- name: "(Setup: All NGINX) Dynamically Generate NGINX HTTP Configuration Files"
  template:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/http/{{ item | basename | regex_replace('\.j2','') }}
    backup: yes
  with_fileglob:
    - "../templates/http/*.j2"
  when: http_template_enable
  notify: "(Handler: All OSs) Reload NGINX"
