---

  - name: Install package dependencies
    apt: name={{ item }} state=present
    with_items:
      - libffi-dev
      - openjdk-8-jdk
      - openjdk-8-jre
      - python-dev
      - libfuzzy-dev
    become: yes
