---
  # If not working perform apt-get install dirmngr
  - name: add key
    become: true 
    apt_key:
      keyserver: "hkp://keyserver.ubuntu.com:80"
      id: "9DA31620334BD75D9DCB49F368818C72E52529D4"
      state: present
    tags:
      - mongodb_install_addkey

  - name: add official mongo repository
    become: true
    apt_repository:
      filename: "mongodb-org-4.0.list"
      repo: "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main"
      state: "present"
      update_cache: true
      validate_certs: true
    tags:
      - mongodb_install_addrepo

  - name: install mongodb-org
    become: true 
    apt:
      name: "mongodb-org=4.0.0"
      state: "present"
    tags:
      - mongodb_install