---
- hosts: 'all'
  become: true
  vars:
    user: docker
    docker_home: /home/docker/docker-registry
  tasks:
  - synchronize:
      src: "./"
      dest: '{{ docker_home }}'
  - docker_compose:
      project_src: '{{ docker_home }}'
      state: present
      build: yes
      restarted: yes
