---
  - name: Bootstrap a host without python2 installed
    raw: "apt-get update && apt-get -y install python"
    tags:
      - base-setup

  - name: Gather facts manually
    setup: 
      gather_subset:
        - all

  - name: Install basic packages
    apt: state=present pkg={{ item }} update_cache=yes
    with_items:
      - sudo
      - python-pip
      - vim
      - screen
      - tcpdump
      - htop
      - tmux
      - git
      - zsh
      - telnet 
      - ftp
      - netcat
      - source-highlight
      - xclip
      - xauth
      - p7zip-full
      - unrar
      - wget
      - curl
      - rsync
      - htop
      - iotop
      - strace
      - whois 
      - screen
      - iperf
      - ntpdate
      - ufw
      - openvpn
      - unzip
      - iptables-persistent
      - python-virtualenv
      - virtualenv
      - virtualenvwrapper
      - libffi-dev
      - openjdk-8-jdk
      - openjdk-8-jre
      - python-dev
      - libfuzzy-dev
      - libmariadbclient-dev
      - apache2
      - libapache2-mod-wsgi
      - keychain
      - celeryd
      - rabbitmq-server
      - smartmontools
    tags:
      - base-setup
