---

  - name: installing monitoring packages
    become: yes
    apt: state=latest pkg={{ item }}
    with_items:
      - nagios-nrpe-server
      - nagios-plugins
    tags:
      - monitoring
      - packages

  - name: upload check_mem.pl
    become: yes
    copy: src=nagios/checks/check_mem.pl dest=/usr/lib/nagios/plugins/ owner=root group=root mode=0755
    tags:
      - monitoring
      - config

  - name: upload nrpe.cfg 
    become: yes
    template: src=monitoring/nrpe.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
    notify:
      - restart nrpe
    tags:
      - monitoring
      - config

  - name: upload base.cfg file for basic checks
    become: yes
    template: src=monitoring/base.cfg dest=/etc/nagios/nrpe.d/base.cfg owner=root group=root mode=0644
    notify: restart nrpe
    tags:
      - config
      - monitoring
      - monitoring-base-config

  - name: check for host specific configuration
    # local_action: "stat path=templates/nagios/host/{{ ansible_hostname }}.cfg.j2"
    local_action: "stat path=templates/nagios/host/{{ ansible_hostname }}.cfg.j2"
    become: no
    register: host_conf
    tags:
      - config
      - monitoring
      - host_config

  - name: upload specific configuration file
    become: yes
    template: src=nagios/host/{{ ansible_hostname }}.cfg.j2 dest=/etc/nagios/nrpe.d/{{ ansible_hostname }}.cfg owner=root group=root mode=0644
    when: host_conf.stat.exists == True
    notify: restart nrpe
    tags:
      - config
      - monitoring
      - host_config

  # - name: upload base configuration for each server
  #   become: yes
  #   template: src=server/{{ ansible_hostname }}.cfg dest=/etc/nagios/ owner=root group=root mode=0644

  # - name: install packages
  #   become: yes
  #   apt: state=latest pkg={{ item }} update_cache=yes
  #   with_items:
  #     - nagios-nrpe-server
  #     - nagios-plugins
  #   tags:
  #     - packages


