---
# Play to fix the Spectre and Meltdown vulnerabilities.

  # - name: Notify distribution version upgrade
  #   debug: msg="{{ ansible_lsb.codename }}"

  - name: apt update && apt dist-upgrade
    become: yes
    apt:
      upgrade: dist
      update-cache: yes
    # when: ansible_distribution == 'Debian' and ansible_distribution_version == '7'


  - name: reboot
    become: yes
    command: shutdown -r 0
    # when: ansible_distribution == 'Debian' and ansible_distribution_version == '7'

