---
- hosts: all
  remote_user: msalinas
  tasks:
          # upload ssh key                
          - authorized_key:
                  user: vivek
                  state: present
                  manage_dir: yes
                  key: "{{ lookup('file', '/home/msalinas/.ssh/id_rsa_hispasec.pub') }}"
