---
- hosts: sentry
  become: true
  tasks:
  - name: Copiar configuraci贸n sitio nginx
    copy:
      src: nginx/sentry.conf
      dest: /etc/nginx/sites-available/sentry.conf
    register: nginx_config
#  - name: Copiar configuraci贸n nginx
#    copy:
#      src: nginx/nginx.conf
#      dest: /etc/nginx/nginx.conf
#    become: true
#    register: nginx_config
  - name: Enlace simb贸lico sitio nginx
    file:
      src: /etc/nginx/sites-available/sentry.conf
      dest: /etc/nginx/sites-enabled/sentry.conf
      state: link
  - name: Borrar sitio por defecto de nginx
    file: path=/etc/nginx/sites-enabled/default state=absent
    become: true
  - name: Reiniciar nginx s贸lo si es necesario
    service:
      name: nginx
      state: restarted
    when: nginx_config.changed
